### ISSUE TITLE
[Chore] Set up Initial project

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#1]
## Why

Set up the Initial project to begin work, includes:
- Create a new project based on [gin-templates](https://github.com/nimblehq/gin-templates)

## Who Benefits?

Developer

**Comment by malparty** [comment]
I think the link to Beego is wrong 🙈

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
I see you chose Tailwind for the UI. It's free for you to explore any option. 

But in case you have not explored Bootstrap yet, I definitely recommend it over Tailwind. 
The reasons are multiple:
- more chance to have Bootstrap on a client project
- Tailwind is more optimized for a full component app like React/Vue/... in an app that works with partial views, you will either have a huge mess of redundant classes, or you will end up with a full SCSS approach where Tailwind barely provides the same as CSS does (with different naming and many `@apply`).
- Tailwind does not have any "components" (cards, alerts, form controls, modals, ...), so either you will reinvent the wheel, or you will need to mention an additional library in this story (e.g. https://daisyui.com/ ).

As said, it's your call, I'm just sharing what I recommend and why 😇

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
What will be the endpoint to verify that the UI is well configured?
Should separate the "Set up initial project" from the "Configure UI library" part? (that will be easier to review the PRs ^^ As the initial scaffold of a project is often huge!!)

**Comment by markgravity** [comment]
> What will be the endpoint to verify that the UI is well configured?
> Should separate the "Set up initial project" from the "Configure UI library" part? (that will be easier to review the PRs ^^ As the initial scaffold of a project is often huge!!)

@malparty thank for all suggestions, I will use the bootstrap and move it to another task ❤️
