### ISSUE TITLE
[API] As a user, I can sign in

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#11]
## Acceptance Criteria

- Create a new endpoint to sign in: `POST api/v1/auth/sign-in`

  - Request:
  ```
  {
    "client_id": "id,
    "client_secret": "secret",
    "email": "markg@gmail.com",
    "password": "xxxx",
  }
  ```
  - Response: Token 

- Token
```
{
  "type": "token",
  "attributes":  {
    "access_token": "access token",
    "token_type": "bearer",
    "expires_in": 7200,
    "refresh_token": "refresh token",
    "scope": "scopes"
  }
}
```

- Using the query from #26 to get the response object

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
Do we plan to have an API version of this project or will it be a UI only? 👀 

If UI only, an access token in JSON might not be very useful 🤔 Web apps use sessions to manage a connection.
Which makes me think: What library will we use for authentication? :)
