### ISSUE TITLE
[Chore] Set up CI pipline

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#2]
## Why

Set up CI to run tests:
- Use GitHub Actions and create test workflow
- Run unit tests

## Who Benefits?

Developer

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
I think we can keep the singular for "pipeline", as there is only 1 pipeline, that will coordinate multiple workflows (ex. Build, Lint, Unit Tests, UI tests, ...).

Update: same suggestion for https://github.com/markgravity/golang-ic/issues/3

**Comment by markgravity** [comment]
> pipeline

updated 🙏
