### ISSUE TITLE
[Backend] As a user, I can upload a keyword file.

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#29]
## Acceptance Criteria

- Receiving an input CSV, and using #34 to collect the data from keywords

**Comment by malparty** [comment]
Is there a reason why the model is not just `Keyword`? 👀 

By just the naming, I would assume ("assumption") that a model called `KeywordDetail` contains the attributes of 1 specific Detail associated to a `Keyword` object.
In other worlds, a one-to-many association table like this:

![image](https://github.com/markgravity/golang-ic/assets/77609814/a7a80ef5-a216-4c29-8901-b464b0ff7926)

This question then brings me to a near-related topic: Do you plan to use a DB diagram? :)
If yes, you can use https://dbdiagram.io/ with the account in 1Password.

**Comment by markgravity** [comment]
@malparty it's a bit confuse here, let me update the description.
The KeywordDetail here is the KeywordDetailResponse and it will be use in the API 🙏
