### ISSUE TITLE
[Chore] Set up the CD pipeline

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#3]
## Why

Set up the CD pipelines
- Use GitHub Actions and create a deploy workflow
- Deploy to Heroku
- Support both staging and production releases

## Who Benefits?

Developer

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
Will that include both PROD and staging? Or only staging? Can be nice to specify this in the story :)

**Comment by markgravity** [comment]
> Will that include both PROD and staging? Or only staging? Can be nice to specify this in the story :)

@malparty nice catch. The IC requires both staging and production releases.
Updated it 🙏
