### ISSUE TITLE
[Backend] As a user, I can get the result data of multi keywords from Google Search

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#44]
## Acceptance Criteria

- Setup worker using [work](https://github.com/gocraft/work)
- Queue Keyword crawling in the background

**Comment by malparty** [comment]
The title of the user story is confusing IMO (this suggestion also applies for #34)
- using `get` instead of `view` (used for the other stories)
- it's not clear what is expected when we read the story (and when we read the AC, it feels "unexpected")


What about:

```
As a user, I can view the result data shortly after I have uploaded a keywords file
```

**Comment by malparty** [comment]
another possibility would be:

```
As a user, when I upload a keywords file, the results are automatically fetched from Google Search.
```
