### ISSUE TITLE
[API] As a user, I can search across all keywords

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#6]
## Acceptance Criteria

- Base on #8 , add a new query parameter `search={text}`
  - `GET api/v1/keywords?search={text}`
  - Header: Authorization (bearer token)
  - Request: search
  - Response: List of Keyword 

- Keyword
```
{
  "type": "keyword",
  "id":  100,
  "attributes": {
    "text": "d4",
    "status": "completed",
    "created_at": "2021-04-02T09:55:13Z",
   "updated_at": "2021-04-02T09:55:13Z"
  }
}
```

- Using the updated query from #28 to filter the result by the search text

**Comment by malparty** [comment]
_🦄 Resolved 🦄_

Should we use `keywords` pluralized? As usually controllers are plural names (except `auth`), and so we have a good consistency between the route names and the controller names :)

`api/v1/keywords?search={text}`

**Comment by markgravity** [comment]
> 

Good point. Let me update it 🙏

**Comment by malparty** [comment]
By the way this one (and some others) are still not JSON API compliant 😇
