### ISSUE TITLE
[API] As a user, I can upload a keyword file.

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#7]
## Acceptance Criteria

- Create a new endpoint to upload CSV file and parse the Google Search result: `POST api/v1/keywords/upload`

  - Request: multipart/form-data
  - Response: empty

  - Example CSV:
  ```
  go
  lang
  API
  file
  ```
- Using #29 to begin process the keywords

**Comment by malparty** [comment]
> Response: 200 OK

Should we just specify the response body? Because the status code will depends on the request's outcomes (from network, infra, config, up to user unprocessable params, ...).

**Comment by markgravity** [comment]
> > Response: 200 OK
> 
> Should we just specify the response body? Because the status code will depends on the request's outcomes (from network, infra, config, up to user unprocessable params, ...).

I think it only return 200 OK without a body 🤔

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
Yes, an "empty" response body is perfectly fine, what I mean is to not have "200 OK" as an AC, because that does not depends on the spec, but on how the endpoint is called (and on the infra state, and many many other things).

What about that?

```
Response: empty
```

**Comment by markgravity** [comment]
> Yes, an "empty" response body is perfectly fine, what I mean is to not have "200 OK" as an AC, because that does not depends on the spec, but on how the endpoint is called (and on the infra state, and many many other things).
> 
> What about that?
> 
> ```
> Response: empty
> ```

@malparty  Updated 🙏
