### ISSUE TITLE
[API] As a user, I can view the search result information for each keyword.

### ISSUE THREAD

**Issue by markgravity** [markgravity/golang-ic#9]
## Acceptance Criteria

- Create a new endpoint to get the keyword detail by id:  `GET api/v1/keywords/{id}`
  - Header: Authorization (bearer token)
  - Response:  Keyword

- Keyword
```
{
  "type": "keyword_detail",
  "id":  100,
  "attributes": {
    "text": "d4",
    "status": "completed",
    "created_at": "2021-04-02T09:55:13Z",
   "updated_at": "2021-04-02T09:55:13Z"
  }
}
```
 
- Using #31 to get the KeywordDetail by id

**Comment by malparty** [comment]
_🦄 Resolved 🦄_
Same suggestion `GET api/v1/keyword/{id}` to use "plural" like this: `GET api/v1/keywords/{id}`

**Comment by markgravity** [comment]
> Same suggestion `GET api/v1/keyword/{id}` to use "plural" like this: `GET api/v1/keywords/{id}`

Updated 🙏
